services:
  - type: web
    name: bitewise-backend
    runtime: docker
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: bitewise-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: bitewise-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: bitewise-db
          property: password
      - key: APP_JWT_SECRET
        generateValue: true
      - key: EDAMAM_APP_ID
        sync: false
      - key: EDAMAM_APP_KEY
        sync: false

databases:
  - name: bitewise-db
    databaseName: bitewise_db
    user: bitewise_user